"""
RECORDING GAP VISUALIZATION SCRIPT
==================================
PURPOSE:
    Reads all cleaned route data files (Excel or CSV) from a single folder,
    separates them into morning (AM) and afternoon (PM) groups, and creates
    a temperature-versus-time plot showing data collection coverage.
    The script highlights periods where:
    • No pocket lab collected data
        (shown in red)
    • Only some pocket labs collected data
        (shown in orange)
    This makes it easy to identify recording gaps, device failures,
    or periods when only one collector was recording.

OUTPUT:
One PNG image

HOW TO USE THIS SCRIPT:
    1. Set the folder path in Section 1 below.
    2. Run:
       python recording_gaps_all_plot.py
    3. The plot will be displayed and automatically saved.

EXPECTED INPUT FILES:
    The folder should contain cleaned route files generated by the
    heat mapping combining script, combining_all.py
    Examples:
        combined_R19_06172026_BH_AM_noGPS.xlsx
        combined_R19_06172026_TJ_AM_noGPS.xlsx
        combined_R19_06172026_BH_PM_noGPS.xlsx
        combined_R19_06172026_TJ_PM_noGPS.xlsx

DEPENDENCIES:
pip install pandas matplotlib openpyxl
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.dates as mdates
import os
import glob

# =============================================================================
# SECTION 1: CONFIGURATION — THIS IS THE ONLY SECTION YOU NEED TO EDIT
# =============================================================================

# ── SET YOUR FOLDER PATH HERE ──────────────────────────────────────────────────
FOLDER = r"C:\Users\dresd\USVI_2026\combined_data\0607_R17\all_R17"  # Windows example
# FOLDER = "/Users/yourname/Documents/MyData"    # Mac/Linux example

# Folder containing cleaned route files
# produced by the heat mapping cleaning script, combining_all.py.
# The script will search this folder for:
#   *.xlsx
#   *.xls
#   *.csv
# ──────────────────────────────────────────────────────────────────────────────

# =============================================================================
# END OF USER INPUT — DO NOT EDIT BELOW THIS LINE UNLESS CUSTOMIZING
# =============================================================================

GAP_THRESHOLD_SECONDS = 2


# Maximum allowable gap between consecutive measurements before a break in the plotted
# line is inserted.
# Example:
#   If timestamps jump from:
#       08:01:00
#       08:01:01
#       08:01:15
# a visible break will appear because 14 seconds exceeds this threshold.

# =============================================================================
# SECTION 2: FIND ALL DATA FILES
# =============================================================================

def load_files(folder):
    patterns = ['*.xlsx', '*.xls', '*.csv']
    file_paths = []
    for pattern in patterns:
        file_paths.extend(glob.glob(os.path.join(folder, pattern)))
    return sorted(file_paths)


# Search the specified folder for spreadsheet files.

# =============================================================================
# SECTION 3: READ AND VALIDATE INPUT FILES
# =============================================================================

def read_file(path):
    ext = os.path.splitext(path)[1].lower()
    return pd.read_csv(path) if ext == '.csv' else pd.read_excel(path)


# Read a CSV or Excel file into a pandas DataFrame.

def parse_times(series):
    parsed = pd.to_datetime(series, errors='coerce', format='mixed')
    if parsed.isna().all():
        return pd.to_numeric(series, errors='coerce'), False
    return parsed, True


# Attempt to parse a time column into datetime values.
# Returns:
#     parsed_times : datetime or numeric series
#     is_datetime  : True if parsed as datetime

def load_group(files):
    loaded = []
    for path in files:
        name = os.path.basename(path)
        try:
            df = read_file(path)
        except Exception as e:
            print(f"Warning: Could not read '{name}': {e}")
            continue
        if 'time' not in df.columns or 'temp_probe' not in df.columns:
            print(
                f"Warning: '{name}' missing 'time' or 'temp_probe'. Skipping.")
            continue
        df = df.dropna(subset=['time', 'temp_probe']).copy()
        if df.empty:
            continue
        t, is_dt = parse_times(df['time'])
        df['_t'] = t
        df = df.dropna(subset=['_t']).sort_values('_t').reset_index(drop=True)
        if df.empty:
            continue
        loaded.append((name, df, is_dt))
    return loaded


# Read and validate a collection of files.
# Invalid files automatically skipped.
# Returns:
#     List of tuples: (filename, dataframe, is_datetime)

# =============================================================================
# SECTION 4: DETERMINE DATA COVERAGE BY SECOND
# =============================================================================

def classify_seconds(loaded):
    is_datetime = any(is_dt for _, _, is_dt in loaded)
    all_times = pd.concat([df['_t'] for _, df, _ in loaded])
    global_min = all_times.min()
    # Determine how many files contain data at each second.
    # Returns:
    #    global_min
    #        Earliest timestamp found
    #    global_max_sec
    #        Maximum elapsed second
    #    coverage
    #        Dictionary mapping:
    #            second -> number of files
    #                       containing data
    #    is_datetime
    #        True if timestamps are datetime values

    if is_datetime:
        def to_int_seconds(series):
            return ((series - global_min).dt.total_seconds()).astype(int)

        global_max_sec = int((all_times.max() - global_min).total_seconds())
    else:
        def to_int_seconds(series):
            return (series - global_min).astype(int)

        global_max_sec = int(all_times.max() - global_min)

    # coverage[sec] = number of distinct files with data at that second
    coverage = {}
    for name, df, is_dt in loaded:
        secs = to_int_seconds(df['_t'])
        for s in secs:
            coverage[s] = coverage.get(s, 0) + 1

    return global_min, global_max_sec, coverage, is_datetime


# =============================================================================
# SECTION 5: IDENTIFY GAP REGIONS
# =============================================================================

def find_gap_regions(loaded):
    """
    Classify each second relative to the total number of files in this group:
      - 0 files   -> 'none'
      - 1..N-1    -> 'partial'  (some but not all; only meaningful when N >= 2)
      - N files   -> 'all'      (full coverage, no issue)

    When there is only 1 file, every second is either 'none' or 'all' —
    there is no 'partial' state.

    Analyzes data coverage across all files and identifies periods where
    data collection was incomplete.
    """
    if not loaded:
        return []

    n_files = len(loaded)
    global_min, global_max_sec, coverage, is_datetime = classify_seconds(loaded)

    def sec_to_time(s):
        if is_datetime:
            return global_min + pd.Timedelta(seconds=int(s))
        else:
            return global_min + int(s)

    regions = []
    current_type = None
    run_start = 0

    for s in range(global_max_sec + 1):
        n = coverage.get(s, 0)
        if n == 0:
            stype = 'none'
        elif n < n_files:
            stype = 'partial'  # only relevant when n_files >= 2
        else:
            stype = 'all'

        if stype != current_type:
            if current_type in ('none', 'partial'):
                regions.append({
                    'type': current_type,
                    'start': sec_to_time(run_start),
                    'end': sec_to_time(s),
                })
            current_type = stype
            run_start = s

    if current_type in ('none', 'partial'):
        regions.append({
            'type': current_type,
            'start': sec_to_time(run_start),
            'end': sec_to_time(global_max_sec),
        })

    return regions


# =============================================================================
# SECTION 6: PLOTTING HELPERS
# =============================================================================

def fmt_time(t):
    if isinstance(t, pd.Timestamp):
        return t.strftime('%H:%M:%S')
    return str(t)


# Convert a time value into a readable string.

def set_time_axis(ax, is_datetime):
    """Show only time of day (no date)."""
    if not is_datetime:
        return

    ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
    ax.xaxis.set_major_locator(mdates.AutoDateLocator(minticks=4, maxticks=10))

    plt.setp(ax.xaxis.get_majorticklabels(), rotation=20, ha='right')


def plot_group(ax, files, title):
    loaded = load_group(files)
    n_files = len(loaded)

    if not loaded:
        ax.set_title(title, pad = 12)
        ax.text(0.5, 0.5, 'No valid files', ha='center', va='center',
                transform=ax.transAxes)
        return []

    is_datetime = any(is_dt for _, _, is_dt in loaded)

    # ── Plot lines, split at gaps so no connecting lines ──
    for name, df, is_dt in loaded:
        threshold = (pd.Timedelta(seconds=GAP_THRESHOLD_SECONDS)
                     if is_dt else GAP_THRESHOLD_SECONDS)
        gap_indices = df.index[df['_t'].diff() > threshold].tolist()
        split_points = [0] + gap_indices + [len(df)]

        color = None
        for i in range(len(split_points) - 1):
            seg = df.iloc[split_points[i]:split_points[i + 1]]
            if seg.empty:
                continue
            if color is None:
                parts = name.split("_")
                if len(parts) >= 4:
                    label = parts[3]  # TJ or BH
                else:
                    label = name
                line, = ax.plot(seg['_t'], seg['temp_probe'], label=label)
                color = line.get_color()
            else:
                ax.plot(seg['_t'], seg['temp_probe'], color=color)

    # ── Shade gap regions ──
    regions = find_gap_regions(loaded)

    has_none = False
    has_partial = False
    for r in regions:
        if r['type'] == 'none':
            ax.axvspan(r['start'], r['end'], color='red', alpha=0.25, zorder=0)
            has_none = True
        elif r['type'] == 'partial' and n_files >= 2:
            ax.axvspan(r['start'], r['end'], color='orange', alpha=0.20,
                       zorder=0)
            has_partial = True

    ax.set_title(title, pad = 12)
    ax.set_xlabel('Time')
    ax.set_ylabel('Temp Probe')
    set_time_axis(ax, is_datetime)

    handles, labels = ax.get_legend_handles_labels()
    if has_partial:
        handles.append(mpatches.Patch(color='orange', alpha=0.4,
                                      label="Missing 1 lab's data"))
    if has_none:
        handles.append(mpatches.Patch(color='red', alpha=0.4,
                                      label='No lab has data'))
    ax.legend(handles=handles)

    return regions


# =============================================================================
# SECTION 7: BUILD COVERAGE SUMMARY TEXT
# =============================================================================

def build_summary_text(am_regions, pm_regions, am_count, pm_count):
    """
    Group all 'partial' messages together, then all 'none' messages.
    Skip partial entries for blocks that only have 1 file (not meaningful).
    """
    partial_lines = []
    none_lines = []

    for block_label, regions, n_files in [
        ('AM', am_regions, am_count),
        ('PM', pm_regions, pm_count),
    ]:
        for r in regions:
            line = f"  [{block_label}]  {fmt_time(r['start'])} → {fmt_time(r['end'])}"
            if r['type'] == 'partial' and n_files >= 2:
                partial_lines.append(line)
            elif r['type'] == 'none':
                none_lines.append(line)

    parts = []
    if partial_lines:
        parts.append(
            "At least one pocket lab didn't collect data for time ranging:")
        parts.extend(partial_lines)
    if none_lines:
        if parts:
            parts.append("")
        parts.append("No pocket lab collected data for time ranging:")
        parts.extend(none_lines)

    return "\n".join(parts) if parts else "No coverage gaps detected."


def plot_temp_vs_time(folder):
    all_files = load_files(folder)
    if not all_files:
        print(f"No spreadsheet files found in: {folder}")
        return

    # Current folder = all_R13
    # Parent folder = 0617_R13

    parent_folder = os.path.basename(
        os.path.dirname(os.path.normpath(folder))
    )

    run_label = parent_folder

    am_files, pm_files, other_files = [], [], []
    for path in all_files:
        name = os.path.basename(path).upper()
        if 'AM' in name:
            am_files.append(path)
        elif 'PM' in name:
            pm_files.append(path)
        else:
            other_files.append(path)

    if other_files:
        print("Note: files without 'AM' or 'PM' in name will be skipped:")
        for f in other_files:
            print(f"  {os.path.basename(f)}")

    fig = plt.figure(figsize=(14, 15))
    ax_am = fig.add_axes([0.08, 0.52, 0.88, 0.34])
    ax_pm = fig.add_axes([0.08, 0.04, 0.88, 0.34])

    fig.suptitle(
        f'Time vs Temp Probe  —  {run_label}',
        fontsize=14,
        fontweight='bold',
        y = 0.995
    )

    fig.text(
        0.5,  # centered horizontally
        0.93,  # slightly below main title
        'All pocket lab data, regardless of GPS coordinates',
        ha='center',
        fontsize=10,
        style='italic',
        color='dimgray'
    )

    am_regions = plot_group(ax_am, am_files, 'Morning Block (AM)')
    pm_regions = plot_group(ax_pm, pm_files, 'Afternoon Block (PM)')

    summary = build_summary_text(am_regions, pm_regions,
                                 len(am_files), len(pm_files))
    print(f"\n[{run_label}] Coverage report:\n{summary}")

    fig.text(
        0.08, 0.004,
        summary,
        fontsize=8,
        verticalalignment='top',
        horizontalalignment='left',
        family='monospace',
        color='#333333',
    )

    output_name = f"recording_gaps_{run_label}_noGPS.png"
    output_path = os.path.join(folder, output_name)
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    print(f"\nPlot saved to: {output_path}")
    plt.show()


if __name__ == '__main__':
    plot_temp_vs_time(FOLDER)