"""
RECORDING GAP VISUALIZATION SCRIPT (excluding pocket lab data missing latitude and longitude)
==================================
PURPOSE:
    Reads all cleaned route data files (Excel or CSV) from a single folder,
    separates them into morning (AM) and afternoon (PM) groups, and creates
    a temperature-versus-time plot showing data collection coverage.
    The script highlights periods where:
    • No pocket lab collected data
        (shown in red)
    • Only some pocket labs collected data
        (shown in orange)
    • The team was stopped collecting a kestrel (WBGT) reading
        (shown in light blue — never counted as a gap, even if no
        pocket lab has data during that window)
    This makes it easy to identify recording gaps, device failures,
    or periods when only one collector was recording.

OUTPUT:
One PNG image

HOW TO USE THIS SCRIPT:
    1. Set the folder path in Section 1 below.
    2. List any kestrel CSV file paths in Section 1 (optional).
    3. Run:
       python recording_gaps_excluding_missing_gps_plot.py
    4. The plot will be displayed and automatically saved.

EXPECTED INPUT FILES:
    The folder should contain cleaned route files generated by the
    heat mapping combining script, combining_all.py
    Examples:
        combined_R19_06172026_BH_AM.xlsx
        combined_R19_06172026_TJ_AM.xlsx
        combined_R19_06172026_BH_PM.xlsx
        combined_R19_06172026_TJ_PM.xlsx

    Kestrel (WBGT) files are listed individually (not folder-scanned —
    see KESTREL_FILES below) and must have 'AM' or 'PM' somewhere in
    their filename so the script knows which plot they belong to.

DEPENDENCIES:
pip install pandas matplotlib openpyxl
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.dates as mdates
import datetime
import os
import glob

# =============================================================================
# SECTION 1: CONFIGURATION — THIS IS THE ONLY SECTION YOU NEED TO EDIT
# =============================================================================

# ── SET YOUR FOLDER PATH HERE ──────────────────────────────────────────────────
FOLDER = r"C:\Users\dresd\USVI_2026\combined_data\0621_R27\lat_long_present_R27"  # Windows example
# FOLDER = "/Users/yourname/Documents/MyData"    # Mac/Linux example

# Folder containing cleaned route files
# produced by the heat mapping cleaning script, combining_all.py.
# The script will search this folder for:
#   *.xlsx
#   *.xls
#   *.csv
# ──────────────────────────────────────────────────────────────────────────────

# ── KESTREL FILES (WBGT stop-period data) ──────────────────────────────────────
# List the full path to every kestrel CSV file you want represented on the
# plots. Each file produces its own light-blue "stop" block, placed using
# that file's earliest and latest recorded time. There can be any number
# of kestrel files (including zero) per AM or PM plot.
#
# Each filename MUST contain 'AM' or 'PM' so the script knows which plot
# the stop period belongs to (e.g. "kestrel_R17_AM_stop1.csv").
#
# Leave the list empty ( [] ) if you have no kestrel files for this run.
KESTREL_FILES = [
r"C:\Users\dresd\USVI_2026\raw_data\0621_R27\0621_R27_WBGT_MF_AM.csv"
    # r"C:\Users\dresd\USVI_2026\kestrel_data\kestrel_R17_AM_stop1.csv",
    # r"C:\Users\dresd\USVI_2026\kestrel_data\kestrel_R17_AM_stop2.csv",
    # r"C:\Users\dresd\USVI_2026\kestrel_data\kestrel_R17_PM_stop1.csv",
]
# ──────────────────────────────────────────────────────────────────────────────

# Fixed left-hand edge for each plot's time axis, regardless of when the
# pocket labs' data actually starts.
AXIS_START_AM = datetime.time(9, 45)    # 9:45 AM
AXIS_START_PM = datetime.time(13, 45)   # 1:45 PM

# =============================================================================
# END OF USER INPUT — DO NOT EDIT BELOW THIS LINE UNLESS CUSTOMIZING
# =============================================================================

GAP_THRESHOLD_SECONDS = 2


# Maximum allowable gap between consecutive measurements before a break in the plotted
# line is inserted.
# Example:
#   If timestamps jump from:
#       08:01:00
#       08:01:01
#       08:01:15
# a visible break will appear because 14 seconds exceeds this threshold.

# =============================================================================
# SECTION 2: FIND ALL DATA FILES
# =============================================================================

def load_files(folder):
    patterns = ['*.xlsx', '*.xls', '*.csv']
    file_paths = []
    for pattern in patterns:
        file_paths.extend(glob.glob(os.path.join(folder, pattern)))
    return sorted(file_paths)


# Search the specified folder for spreadsheet files.

# =============================================================================
# SECTION 3: READ AND VALIDATE INPUT FILES
# =============================================================================

def read_file(path):
    ext = os.path.splitext(path)[1].lower()
    return pd.read_csv(path) if ext == '.csv' else pd.read_excel(path)


# Read a CSV or Excel file into a pandas DataFrame.

def parse_times(series):
    parsed = pd.to_datetime(series, errors='coerce', format='mixed')
    if parsed.isna().all():
        return pd.to_numeric(series, errors='coerce'), False
    return parsed, True


# Attempt to parse a time column into datetime values.
# Returns:
#     parsed_times : datetime or numeric series
#     is_datetime  : True if parsed as datetime

def load_group(files):
    loaded = []
    for path in files:
        name = os.path.basename(path)
        try:
            df = read_file(path)
        except Exception as e:
            print(f"Warning: Could not read '{name}': {e}")
            continue
        if 'time' not in df.columns or 'temp_probe' not in df.columns:
            print(
                f"Warning: '{name}' missing 'time' or 'temp_probe'. Skipping.")
            continue
        df = df.dropna(subset=['time', 'temp_probe']).copy()
        if df.empty:
            continue
        t, is_dt = parse_times(df['time'])
        df['_t'] = t
        df = df.dropna(subset=['_t']).sort_values('_t').reset_index(drop=True)
        if df.empty:
            continue
        loaded.append((name, df, is_dt))
    return loaded


# Read and validate a collection of files.
# Invalid files automatically skipped.
# Returns:
#     List of tuples: (filename, dataframe, is_datetime)

# =============================================================================
# SECTION 3B: READ KESTREL (WBGT) STOP-PERIOD FILES
# =============================================================================

def read_kestrel_stop_period(path):
    """
    Read a kestrel CSV and return the (start_time, end_time) span of its
    timestamp column, as datetime.time objects. Only wall-clock time
    matters here — the date in the kestrel file is ignored, since the
    stop block is placed using the date already present in the pocket
    lab data for that plot.

    Expected file layout:
        Rows 1-5 : header / instrument metadata (skipped)
        Row 6+   : data, with timestamps in the first column, e.g.
                   '6/7/2026  10:48:45 AM'   (note the double space)

    Returns None if the file can't be read or has no parseable timestamps.
    """
    name = os.path.basename(path)
    try:
        df = pd.read_csv(path, skiprows=5, header=None, usecols=[0])
    except Exception as e:
        print(f"Warning: Could not read kestrel file '{name}': {e}")
        return None

    raw = df.iloc[:, 0].dropna().astype(str)
    raw = raw.str.replace(r'\s+', ' ', regex=True).str.strip()
    parsed = pd.to_datetime(raw, errors='coerce', format='mixed').dropna()

    if parsed.empty:
        print(f"Warning: No valid timestamps found in kestrel file '{name}'.")
        return None

    return parsed.min().time(), parsed.max().time()


# =============================================================================
# SECTION 4: DETERMINE DATA COVERAGE BY SECOND
# =============================================================================

def classify_seconds(loaded):
    is_datetime = any(is_dt for _, _, is_dt in loaded)
    all_times = pd.concat([df['_t'] for _, df, _ in loaded])
    global_min = all_times.min()
    # Determine how many files contain data at each second.
    # Returns:
    #    global_min
    #        Earliest timestamp found
    #    global_max_sec
    #        Maximum elapsed second
    #    coverage
    #        Dictionary mapping:
    #            second -> number of files
    #                       containing data
    #    is_datetime
    #        True if timestamps are datetime values

    if is_datetime:
        def to_int_seconds(series):
            return ((series - global_min).dt.total_seconds()).astype(int)

        global_max_sec = int((all_times.max() - global_min).total_seconds())
    else:
        def to_int_seconds(series):
            return (series - global_min).astype(int)

        global_max_sec = int(all_times.max() - global_min)

    # coverage[sec] = number of distinct files with data at that second
    coverage = {}
    for name, df, is_dt in loaded:
        secs = to_int_seconds(df['_t'])
        for s in secs:
            coverage[s] = coverage.get(s, 0) + 1

    return global_min, global_max_sec, coverage, is_datetime


# =============================================================================
# SECTION 5: IDENTIFY GAP REGIONS
# =============================================================================

def find_gap_regions(loaded, stop_intervals=None):
    """
    Classify each second relative to the total number of files in this group:
      - 0 files   -> 'none'
      - 1..N-1    -> 'partial'  (some but not all; only meaningful when N >= 2)
      - N files   -> 'all'      (full coverage, no issue)

    When there is only 1 file, every second is either 'none' or 'all' —
    there is no 'partial' state.

    stop_intervals : optional list of (start, end) datetime/Timestamp pairs
        marking known "stop" periods (e.g. kestrel WBGT readings) during
        which the team was intentionally stationary. Any second inside
        one of these windows is always treated as 'all' (fully covered),
        even if the pocket labs themselves recorded nothing there — so
        it is never reported as a gap.

    Analyzes data coverage across all files and identifies periods where
    data collection was incomplete.
    """
    if not loaded:
        return []

    if stop_intervals is None:
        stop_intervals = []

    n_files = len(loaded)
    global_min, global_max_sec, coverage, is_datetime = classify_seconds(loaded)

    def sec_to_time(s):
        if is_datetime:
            return global_min + pd.Timedelta(seconds=int(s))
        else:
            return global_min + int(s)

    def dt_to_sec(dt):
        if is_datetime:
            return int((dt - global_min).total_seconds())
        else:
            return int(dt - global_min)

    # Convert stop intervals into second-offsets and clip to the data range.
    stop_ranges_sec = []
    for start_dt, end_dt in stop_intervals:
        s_sec, e_sec = dt_to_sec(start_dt), dt_to_sec(end_dt)
        if e_sec < s_sec:
            s_sec, e_sec = e_sec, s_sec
        s_sec = max(s_sec, 0)
        e_sec = min(e_sec, global_max_sec)
        if s_sec <= e_sec:
            stop_ranges_sec.append((s_sec, e_sec))

    def in_stop(s):
        return any(start <= s <= end for start, end in stop_ranges_sec)

    regions = []
    current_type = None
    run_start = 0

    for s in range(global_max_sec + 1):
        if in_stop(s):
            stype = 'all'  # kestrel stop period — never a gap
        else:
            n = coverage.get(s, 0)
            if n == 0:
                stype = 'none'
            elif n < n_files:
                stype = 'partial'  # only relevant when n_files >= 2
            else:
                stype = 'all'

        if stype != current_type:
            if current_type in ('none', 'partial'):
                regions.append({
                    'type': current_type,
                    'start': sec_to_time(run_start),
                    'end': sec_to_time(s),
                })
            current_type = stype
            run_start = s

    if current_type in ('none', 'partial'):
        regions.append({
            'type': current_type,
            'start': sec_to_time(run_start),
            'end': sec_to_time(global_max_sec),
        })

    return regions


# =============================================================================
# SECTION 6: PLOTTING HELPERS
# =============================================================================

def fmt_time(t):
    if isinstance(t, pd.Timestamp):
        return t.strftime('%H:%M:%S')
    return str(t)


# Convert a time value into a readable string.

def set_time_axis(ax, is_datetime):
    """Show only time of day (no date)."""
    if not is_datetime:
        return

    ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
    ax.xaxis.set_major_locator(mdates.AutoDateLocator(minticks=4, maxticks=10))

    plt.setp(ax.xaxis.get_majorticklabels(), rotation=20, ha='right')


def plot_group(ax, files, title, kestrel_paths=None, axis_start_time=None):
    """
    kestrel_paths    : list of kestrel CSV paths belonging to this block
                        (AM or PM). Each becomes its own light-blue stop
                        block. May be empty/None.
    axis_start_time  : datetime.time to use as the fixed left edge of the
                        x-axis (e.g. 9:45 AM for the AM plot). May be None.

    Returns (regions, handles, labels). No legend is drawn on the axes
    itself — handles/labels are returned so the caller can combine AM and
    PM into a single figure-level legend.
    """
    kestrel_paths = kestrel_paths or []
    loaded = load_group(files)
    n_files = len(loaded)

    if not loaded:
        ax.set_title(title, pad = 12)
        ax.text(0.5, 0.5, 'No valid files', ha='center', va='center',
                transform=ax.transAxes)
        return [], [], []

    is_datetime = any(is_dt for _, _, is_dt in loaded)
    all_times = pd.concat([df['_t'] for _, df, _ in loaded])
    global_min = all_times.min()

    # ── Build "stop period" windows from kestrel files (light blue) ──
    stop_intervals = []
    if kestrel_paths and is_datetime:
        ref_date = global_min.date()
        for path in kestrel_paths:
            result = read_kestrel_stop_period(path)
            if result is None:
                continue
            start_t, end_t = result
            start_dt = pd.Timestamp.combine(ref_date, start_t)
            end_dt = pd.Timestamp.combine(ref_date, end_t)
            stop_intervals.append((start_dt, end_dt))
    elif kestrel_paths and not is_datetime:
        print(f"Warning: '{title}' timestamps aren't recognized as dates/"
              f"times — skipping kestrel stop-period overlay.")

    # ── Plot lines, split at gaps so no connecting lines ──
    for name, df, is_dt in loaded:
        threshold = (pd.Timedelta(seconds=GAP_THRESHOLD_SECONDS)
                     if is_dt else GAP_THRESHOLD_SECONDS)
        gap_indices = df.index[df['_t'].diff() > threshold].tolist()
        split_points = [0] + gap_indices + [len(df)]

        color = None
        for i in range(len(split_points) - 1):
            seg = df.iloc[split_points[i]:split_points[i + 1]]
            if seg.empty:
                continue
            if color is None:
                parts = name.split("_")
                if len(parts) >= 4:
                    label = parts[3]  # TJ or BH
                else:
                    label = name
                line, = ax.plot(seg['_t'], seg['temp_probe'], label=label)
                color = line.get_color()
            else:
                ax.plot(seg['_t'], seg['temp_probe'], color=color)

    # ── Shade gap regions (kestrel stop periods are excluded from these) ──
    regions = find_gap_regions(loaded, stop_intervals=stop_intervals)

    has_none = False
    has_partial = False
    for r in regions:
        if r['type'] == 'none':
            ax.axvspan(r['start'], r['end'], color='red', alpha=0.25, zorder=0)
            has_none = True
        elif r['type'] == 'partial' and n_files >= 2:
            ax.axvspan(r['start'], r['end'], color='orange', alpha=0.20,
                       zorder=0)
            has_partial = True

    # ── Shade kestrel stop periods (drawn above red/orange) ──
    has_stop = False
    for start_dt, end_dt in stop_intervals:
        ax.axvspan(start_dt, end_dt, color='#77F79B', alpha=0.35, zorder=1)
        has_stop = True

    # ── Shade the 15 minutes immediately before the first kestrel reading ──
    has_pre_kestrel = False
    if stop_intervals:
        first_kestrel_start = min(start for start, _ in stop_intervals)
        pre_start = first_kestrel_start - pd.Timedelta(minutes=15)
        ax.axvspan(pre_start, first_kestrel_start, color='#CCDFFC',
                   alpha=1,
                   zorder=0.5)
        has_pre_kestrel = True


    ax.set_title(title, pad = 12)
    ax.set_xlabel('Time')
    ax.set_ylabel('Temp Probe')
    set_time_axis(ax, is_datetime)

    # ── Fixed axis start time (e.g. 9:45 AM / 1:45 PM) ──
    if is_datetime and axis_start_time is not None:
        left_bound = pd.Timestamp.combine(global_min.date(), axis_start_time)
        ax.set_xlim(left=left_bound)

    handles, labels = ax.get_legend_handles_labels()
    if has_stop:
        handles.append(mpatches.Patch(color='#77F79B', alpha=0.5,
                                      label='Pocket lab stop (kestrel reading)'))
    if has_pre_kestrel:
        handles.append(mpatches.Patch(color='#CCDFFC', alpha=0.6,
                                      label='15 min before first kestrel reading'))
    if has_partial:
        handles.append(mpatches.Patch(color='orange', alpha=0.4,
                                      label="Missing 1 lab's data"))
    if has_none:
        handles.append(mpatches.Patch(color='red', alpha=0.4,
                                      label='No lab has data'))

    return regions, handles, labels


# =============================================================================
# SECTION 7: BUILD COVERAGE SUMMARY TEXT
# =============================================================================

def build_summary_text(am_regions, pm_regions, am_count, pm_count):
    """
    Group all 'partial' messages together, then all 'none' messages.
    Skip partial entries for blocks that only have 1 file (not meaningful).
    Kestrel stop periods never appear here, since find_gap_regions already
    excludes them from the 'none'/'partial' classification.
    """
    partial_lines = []
    none_lines = []

    for block_label, regions, n_files in [
        ('AM', am_regions, am_count),
        ('PM', pm_regions, pm_count),
    ]:
        for r in regions:
            line = f"  [{block_label}]  {fmt_time(r['start'])} → {fmt_time(r['end'])}"
            if r['type'] == 'partial' and n_files >= 2:
                partial_lines.append(line)
            elif r['type'] == 'none':
                none_lines.append(line)

    parts = []
    if partial_lines:
        parts.append(
            "At least one pocket lab didn't collect data for time ranging:")
        parts.extend(partial_lines)
    if none_lines:
        if parts:
            parts.append("")
        parts.append("No pocket lab collected data for time ranging:")
        parts.extend(none_lines)

    return "\n".join(parts) if parts else "No coverage gaps detected."


def plot_temp_vs_time(folder):
    all_files = load_files(folder)
    if not all_files:
        print(f"No spreadsheet files found in: {folder}")
        return

    # Current folder = all_R13
    # Parent folder = 0617_R13

    parent_folder = os.path.basename(
        os.path.dirname(os.path.normpath(folder))
    )

    run_label = parent_folder

    # If a kestrel file happens to live in the same FOLDER, don't let the
    # automatic scan above also pick it up and try to read it as a
    # pocket-lab file (it has a different layout and will just fail).
    kestrel_path_set = {os.path.abspath(p) for p in KESTREL_FILES}

    am_files, pm_files, other_files = [], [], []
    for path in all_files:
        if os.path.abspath(path) in kestrel_path_set:
            continue
        name = os.path.basename(path).upper()
        if 'AM' in name:
            am_files.append(path)
        elif 'PM' in name:
            pm_files.append(path)
        else:
            other_files.append(path)

    if other_files:
        print("Note: files without 'AM' or 'PM' in name will be skipped:")
        for f in other_files:
            print(f"  {os.path.basename(f)}")

    # ── Sort kestrel files into AM / PM by filename ──
    kestrel_am, kestrel_pm, kestrel_other = [], [], []
    for path in KESTREL_FILES:
        name = os.path.basename(path).upper()
        if 'AM' in name:
            kestrel_am.append(path)
        elif 'PM' in name:
            kestrel_pm.append(path)
        else:
            kestrel_other.append(path)

    if kestrel_other:
        print("Note: kestrel files without 'AM' or 'PM' in name will be skipped:")
        for f in kestrel_other:
            print(f"  {os.path.basename(f)}")

    fig = plt.figure(figsize=(14, 15))
    ax_am = fig.add_axes([0.08, 0.52, 0.88, 0.34])
    ax_pm = fig.add_axes([0.08, 0.04, 0.88, 0.34])

    fig.suptitle(
        f'Time vs Temp Probe  —  {run_label}',
        fontsize=14,
        fontweight='bold',
        y = 0.995
    )

    fig.text(
        0.5,  # centered horizontally
        0.93,  # slightly below main title
        'All pocket lab data, regardless of GPS coordinates',
        ha='center',
        fontsize=10,
        style='italic',
        color='dimgray'
    )

    am_regions, am_handles, am_labels = plot_group(
        ax_am, am_files, 'Morning Block (AM)',
        kestrel_paths=kestrel_am, axis_start_time=AXIS_START_AM)
    pm_regions, pm_handles, pm_labels = plot_group(
        ax_pm, pm_files, 'Afternoon Block (PM)',
        kestrel_paths=kestrel_pm, axis_start_time=AXIS_START_PM)

    # ── Combine AM + PM legend entries into a single figure-level legend ──
    # (use each handle's own get_label() — patch handles aren't reflected
    # in the separate labels list returned by get_legend_handles_labels())
    combined = {}
    for handles in (am_handles, pm_handles):
        for h in handles:
            l = h.get_label()
            if l and l not in combined:
                combined[l] = h

    if combined:
        fig.legend(
            list(combined.values()), list(combined.keys()),
            loc='upper center',
            bbox_to_anchor=(0.5, 0.905),
            ncol=len(combined),
            frameon=True,
            fontsize=9,
        )

    summary = build_summary_text(am_regions, pm_regions,
                                 len(am_files), len(pm_files))
    print(f"\n[{run_label}] Coverage report:\n{summary}")

    fig.text(
        0.08, 0.004,
        summary,
        fontsize=8,
        verticalalignment='top',
        horizontalalignment='left',
        family='monospace',
        color='#333333',
    )

    output_name = f"recording_gaps_{run_label}.png"
    output_path = os.path.join(folder, output_name)
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    print(f"\nPlot saved to: {output_path}")
    plt.show()


if __name__ == '__main__':
    plot_temp_vs_time(FOLDER)