---
title: "EDA"
format: html
---

```{r}
library(tidyverse)
library(readxl)
library(dplyr)
```

```{r}

R31_kestrel <- read_csv("raw_data/0608_R31_HL_Kestrel_AM.csv", skip=3)

head(R31_kestrel)

R31_kestrel <- R31_kestrel[-1, ]

R31_kestrel$Temperature <- as.numeric(R31_kestrel$Temperature)
R31_kestrel$`Wet Bulb Temp` <- as.numeric(R31_kestrel$`Wet Bulb Temp`)

R31_kestrel <- R31_kestrel |> 
  mutate(across(4:12, as.numeric))

R31_kestrel$`FORMATTED DATE_TIME` <-
  as.POSIXct(R31_kestrel$`FORMATTED DATE_TIME`)
```

```{r}

# ggplot(R31_kestrel, aes(x = `FORMATTED DATE_TIME`, y = Temperature)) +
#   geom_line() +
#   scale_x_datetime(
#     date_breaks = "15 min",
#     date_labels = "%H:%M"
#   ) +
#   theme_bw() +
#   labs(x = "Time")
# 
# ggplot(R31_kestrel, aes(x = `FORMATTED DATE_TIME`, y = `Wet Bulb Temp`)) +
#   geom_line() +
#   scale_x_datetime(
#     date_breaks = "15 min",
#     date_labels = "%H:%M"
#   ) +
#   theme_bw() +
#   labs(x = "Time")




vars_to_plot <- c(
  "Temperature",
  "Wet Bulb Temp",
  "Globe Temperature",
  "Relative Humidity",
  "Barometric Pressure",
  "Altitude",
  "Station Pressure",
  "Wind Speed",
  "Heat Index",
  "Dew Point",
  "Density Altitude"
)

for (v in vars_to_plot) {
  p <- ggplot(R31_kestrel, aes(x = `FORMATTED DATE_TIME`, y = .data[[v]])) +
    geom_line() +
    scale_x_datetime(
      date_breaks = "15 min",
      date_labels = "%H:%M"
    ) +
    theme_bw() +
    labs(
      x = "Time",
      y = v,
      title = v
    )
  
  print(p)
}

```
